### PR TITLE
moved css to styles.css and  moved tmp to js folder

### PR DESCRIPTION
**Pull request by reimo**
moved css to styles.css and more cleanup, moved tmp to js folder

### CODE REVIEW

**Comment by SCBuergel** [comment]
still lots of double classes - why would you have dedicated classes that are *exactly* identical (e.g. `how-hopr-work`, `why-hopr`, `who-is-hopr`) just for one section and then copy paste it? Rather just make one clean class that is used for all three sections e.g. `mainSection`.

**Comment by SCBuergel** [comment]
also still inconsistent indentation (tabs vs spaces, 2 vs 4 spaces) and newlines. As outlined in the ticket, this code needs to be clean and minimal.

**Comment by SCBuergel** [comment]
Comparing the automatic builds [before](https://hoprnet.netlify.com/assets/) vs [after](https://5d7f68d552ec700008cf7134--hoprnet.netlify.com/assets/) this PR, the following things broke:
1. animascii animiation is no longer works
2. ascii-art looks different due to change in whitespace
3. gray background in WHO section is gone

**Comment by reimo** [comment]
Hi, Fixed and PR'd to the new branch

**Pull request closed without merging**
